export const content = {
  ar: {
    meta: {
      title: 'FORM | تصوّر عارض منتجات ثلاثي الأبعاد',
      description:
        'عارض ثلاثي الأبعاد ثنائي اللغة لتجربة مواصفات باب صناعي داخل المتصفح، من دون أسعار أو طلبات أو إرسال بيانات.',
    },
    brand: 'FORM',
    brandAria: 'العودة إلى بداية FORM',
    language: 'English',
    languageLabel: 'Switch to English',
    eyebrow: 'تصوّر هندسي تفاعلي · داخل المتصفح',
    title: 'حوّل مواصفات الباب إلى قرار بصري.',
    description:
      'نموذج Frontend يربط بين المقاس والخامة واتجاه الفتح وشكل الإكسسوارات. صُمم لتوضيح كيف يمكن دعم محادثات التصنيع والمبيعات قبل بناء نظام عروض أسعار أو طلبات حقيقي.',
    trust: 'نموذج إجرائي · لا أسعار · لا طلبات · لا إرسال بيانات',
    viewerLabel: 'عارض الباب ثلاثي الأبعاد',
    viewerHint: 'اسحب للدوران · حرّك العجلة للتقريب',
    viewerLoading: 'يتم تجهيز النموذج ثلاثي الأبعاد…',
    viewerUnavailable:
      'تعذّر تشغيل العرض ثلاثي الأبعاد على هذا الجهاز. ما زال بإمكانك تعديل المواصفات وقراءتها أدناه.',
    sample: 'SAMPLE CONFIGURATION',
    controls: {
      title: 'مواصفات العرض',
      description: 'كل تغيير يظهر فورًا على النموذج ويبقى داخل المتصفح.',
      finish: 'تشطيب السطح',
      handle: 'تشطيب المقبض',
      width: 'العرض',
      height: 'الارتفاع',
      opening: 'جهة المفصلات',
      left: 'يسار',
      right: 'يمين',
      angle: 'زاوية الفتح',
      exploded: 'عرض تفكيكي للمكوّنات',
      reset: 'إعادة الإعدادات',
    },
    finishes: [
      { id: 'oak', label: 'بلوط طبيعي', color: '#a97849' },
      { id: 'walnut', label: 'جوز داكن', color: '#5f3825' },
      { id: 'charcoal', label: 'فحمي مطفي', color: '#25282c' },
    ],
    handles: [
      { id: 'brass', label: 'نحاسي', color: '#c9a45d' },
      { id: 'black', label: 'أسود', color: '#161719' },
      { id: 'steel', label: 'فولاذي', color: '#aeb4ba' },
    ],
    summary: {
      eyebrow: 'ورقة مواصفة فورية',
      title: 'النسخة المعروضة',
      dimension: 'المقاس الاسمي',
      finish: 'السطح',
      handle: 'المقبض',
      opening: 'المفصلات',
      state: 'وضع العرض',
      exploded: 'تفكيكي',
      assembled: 'مجمّع',
      note: 'هذه القيم نموذجية للعرض وليست رسومات تصنيع أو عرض سعر معتمدًا.',
    },
    footer:
      'تصوّر يربط الهندسة الصناعية بتجربة المنتج الرقمية. WebGL يعمل محليًا داخل المتصفح.',
  },
  en: {
    meta: {
      title: 'FORM | 3D Product Viewer Concept',
      description:
        'A bilingual browser-based 3D door configurator concept with no pricing, ordering, or data submission.',
    },
    brand: 'FORM',
    brandAria: 'Return to the start of FORM',
    language: 'العربية',
    languageLabel: 'التبديل إلى العربية',
    eyebrow: 'Interactive engineering concept · Browser-based',
    title: 'Turn door specifications into a visual decision.',
    description:
      'A frontend model connecting dimensions, finish, opening direction, and hardware. It demonstrates how manufacturing and sales conversations could be supported before a real quotation or order system is built.',
    trust: 'Procedural model · No pricing · No orders · No data submission',
    viewerLabel: 'Interactive 3D door viewer',
    viewerHint: 'Drag to orbit · Scroll to zoom',
    viewerLoading: 'Preparing the 3D model…',
    viewerUnavailable:
      'The 3D view is unavailable on this device. You can still configure and review the specifications below.',
    sample: 'SAMPLE CONFIGURATION',
    controls: {
      title: 'Viewer specifications',
      description: 'Every change updates the model instantly and stays in your browser.',
      finish: 'Surface finish',
      handle: 'Handle finish',
      width: 'Width',
      height: 'Height',
      opening: 'Hinge side',
      left: 'Left',
      right: 'Right',
      angle: 'Opening angle',
      exploded: 'Exploded component view',
      reset: 'Reset configuration',
    },
    finishes: [
      { id: 'oak', label: 'Natural oak', color: '#a97849' },
      { id: 'walnut', label: 'Dark walnut', color: '#5f3825' },
      { id: 'charcoal', label: 'Matte charcoal', color: '#25282c' },
    ],
    handles: [
      { id: 'brass', label: 'Brass', color: '#c9a45d' },
      { id: 'black', label: 'Black', color: '#161719' },
      { id: 'steel', label: 'Steel', color: '#aeb4ba' },
    ],
    summary: {
      eyebrow: 'Instant specification sheet',
      title: 'Displayed configuration',
      dimension: 'Nominal size',
      finish: 'Surface',
      handle: 'Handle',
      opening: 'Hinges',
      state: 'Viewer state',
      exploded: 'Exploded',
      assembled: 'Assembled',
      note: 'These values are illustrative and are not manufacturing drawings or an approved quotation.',
    },
    footer:
      'A concept connecting industrial engineering with digital product experience. WebGL runs locally in the browser.',
  },
}
